"use client";
import {useEffect,useState} from "react";
export default function ProjectControl({params}:{params:Promise<{id:string}>}){const[id,setId]=useState("");const[p,setP]=useState<any>(null);const[tab,setTab]=useState("overview");const[key,setKey]=useState("");const[value,setValue]=useState("");const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
useEffect(()=>{params.then(x=>setId(x.id))},[params]);useEffect(()=>{if(id)load()},[id]);async function load(){const r=await fetch("/api/projects/"+id);const x=await r.json();if(r.ok)setP(x.project)}async function deploy(){setBusy(true);setMsg("");const r=await fetch("/api/projects/"+id+"/deploy",{method:"POST"});const x=await r.json();setMsg(r.ok?"Deployment queued.":x.error||"Deployment failed");setBusy(false);load()}async function addEnv(){if(!key||!value)return;setBusy(true);const r=await fetch("/api/projects/"+id+"/environment",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({key,value})});setMsg(r.ok?"Environment variable saved.":(await r.json()).error||"Unable to save");setKey("");setValue("");setBusy(false);load()}if(!p)return <main className="service-page"><div className="empty-state">Loading project…</div></main>;
return <main className="service-page"><header className="service-header"><div><a className="muted" href="/dashboard/projects">← Projects</a><h1>{p.name}</h1><p>{p.repositoryUrl||"No repository connected"} · {p.repositoryBranch}</p></div><div className="project-actions"><button className="button" onClick={deploy} disabled={busy}>{busy?"Working…":"Deploy"}</button>{p.publicUrl&&<a className="secondary-button" href={p.publicUrl} target="_blank">Open site ↗</a>}</div></header>{msg&&<div className="notice">{msg}</div>}
<div className="control-status"><b className={p.status==="RUNNING"?"status-running":"status-building"}>● {p.status}</b><span>{p.publicUrl||"Public URL pending deployment"}</span><span>{p.runtimeContainer||"Runtime not provisioned"}</span></div>
<nav className="control-tabs">{["overview","deployments","domains","environment","backups"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>
{tab==="overview"&&<><section className="control-grid"><article className="control-card"><small>RUNTIME</small><h3>{p.runtimeContainer||"Not running"}</h3><p>Port {p.runtimePort||"—"} · Health {p.healthPath}</p></article><article className="control-card"><small>DOMAINS</small><h3>{p.domains?.length||0}</h3><p>{(p.domains||[]).filter((d:any)=>d.verified).length} verified</p></article><article className="control-card"><small>ENVIRONMENT</small><h3>{p.environmentVariables?.length||0}</h3><p>Configured variables</p></article><article className="control-card"><small>BACKUPS</small><h3>{p.backups?.length||0}</h3><p>Recent records</p></article></section><section className="service-card-panel control-section"><b>Project configuration</b><div className="config-grid"><span>Framework <b>{p.framework||"Auto-detect"}</b></span><span>Build <b>{p.buildCommand||"Default"}</b></span><span>Start <b>{p.startCommand||"Default"}</b></span><span>Port <b>{p.port||"Auto"}</b></span></div></section></>}
{tab==="deployments"&&<section className="service-card-panel control-section"><b>Deployment history</b>{(p.deployments||[]).map((d:any)=><div className="service-row" key={d.id}><div><b>{d.commitSha||"Latest commit"}</b><span>{new Date(d.createdAt).toLocaleString()}</span></div><strong>{d.status}</strong><span>{d.server?.name||d.serverId||"Unassigned"}</span></div>)}{!p.deployments?.length&&<div className="empty-state">No deployments yet.</div>}</section>}
{tab==="domains"&&<section className="service-card-panel control-section"><b>Domains</b>{(p.domains||[]).map((d:any)=><div className="service-row" key={d.id}><div><b>{d.name}</b><span>{d.verified?"Verified":"Pending verification"}</span></div><strong>{d.sslEnabled?"SSL ACTIVE":"SSL PENDING"}</strong><span>{d.sslStatus}</span></div>)}{!p.domains?.length&&<div className="empty-state">No domains connected.</div>}</section>}
{tab==="environment"&&<section className="service-card-panel control-section"><b>Environment variables</b><div className="inline-form"><input placeholder="KEY" value={key} onChange={e=>setKey(e.target.value)}/><input placeholder="Value" value={value} onChange={e=>setValue(e.target.value)} type="password"/><button className="button" onClick={addEnv} disabled={busy}>Save</button></div>{(p.environmentVariables||[]).map((v:any)=><div className="service-row" key={v.id}><div><b>{v.key}</b><span>{v.environment}</span></div><strong>••••••••</strong><span>Protected</span></div>)}{!p.environmentVariables?.length&&<div className="empty-state">No variables configured.</div>}</section>}
{tab==="backups"&&<section className="service-card-panel control-section"><b>Backups</b>{(p.backups||[]).map((b:any)=><div className="service-row" key={b.id}><div><b>{b.type}</b><span>{new Date(b.createdAt).toLocaleString()}</span></div><strong>{b.status}</strong><span>{b.retentionDays} days</span></div>)}{!p.backups?.length&&<div className="empty-state">No backups yet.</div>}</section>}</main>}